/*--------------------------------------------------------------------
REEF3D
Copyright 2008-2026 Hans Bihs

This file is part of REEF3D.

REEF3D is free software; you can redistribute it and/or modify it
under the terms of the GNU General Public License as published by
the Free Software Foundation; either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful, but WITHOUT
ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License
for more details.

You should have received a copy of the GNU General Public License
along with this program; if not, see <http://www.gnu.org/licenses/>.
--------------------------------------------------------------------
Author: Hans Bihs
--------------------------------------------------------------------*/

#ifndef WAVE_LIB_WAVEMAKER2ND_H_
#define WAVE_LIB_WAVEMAKER2ND_H_

#include<vector>

class lexer;
class ghostcell;

// Second-order wavemaker correction (Schaffer 1996) for piston and flap
// wavemakers driven by a paddle displacement time series.
//
// The first-order paddle signal is decomposed by FFT, the spurious free
// second-order waves (super- and subharmonic) generated by it are computed
// and the paddle displacement X^(2)(t) that cancels their progressive part
// is added to the input signal.
//
// J = number of evanescent modes per frequency (0 = progressive modes only).
// addQ = 1: include the second-order paddle boundary terms
//           Q = X_z*phi_z - X*phi_xx (Taylor expansion about x=0).
//           Use this when the numerical paddle BC also contains Q (B119 1),
//           i.e. when it behaves like a physical moving paddle.
//        0: the numerical BC is phi_x = X_t exactly at x=0 (no Q),
//           so Q must not be cancelled by the correction either.

class wave_lib_wavemaker2nd
{
public:
    wave_lib_wavemaker2nd();
    ~wave_lib_wavemaker2nd();

    // REEF3D interface: modifies kin[q][1] (displacement at the reference
    // elevation of the paddle) in place. shape: 1 piston, 2 flap
    void correct(lexer*, ghostcell*, double **kin, int ptnum, double h, int shape, double zs, double ze);

    // core: uniformly sampled first-order displacement x (dt), returns x2
    // mode: 1 sub+super, 2 subharmonics only, 3 superharmonics only
    // zs,ze measured from the bed, flap: hinge at zs, displacement given at ze
    // fmin,fmax [Hz]: band of first-order components (fmax<=0: automatic)
    // f2min [Hz]: lowest corrected second-order frequency (<=0: 0.1 x peak frequency)
    // returns number of first-order components used
    static int compute(double g, double h, int shape, double zs, double ze,
                       int mode, int J, int addQ, double fmin, double fmax, double f2min, int nmax,
                       const std::vector<double> &x, double dt, std::vector<double> &x2);

    // lowest level: first-order components on an integer frequency grid
    // omega_n = bin[n]*dw, paddle amplitude Xc[n] (re,im) with
    // X(t) = sum_n Re( Xc[n] exp(i omega_n t) ).
    // Returns second-order paddle amplitudes on bins 1..X2re.size()-1, same convention.
    static void compute_components(double g, double h, int shape, double zs, double ze,
                       int mode, int J, int addQ, double dw, double w2min,
                       const std::vector<int> &bin, const std::vector<double> &Xre, const std::vector<double> &Xim,
                       std::vector<double> &X2re, std::vector<double> &X2im);
};

#endif
