/*--------------------------------------------------------------------
REEF3D
Copyright 2008-2026 Hans Bihs

This file is part of REEF3D.

REEF3D is free software; you can redistribute it and/or modify it
under the terms of the GNU General Public License as published by
the Free Software Foundation; either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful, but WITHOUT
ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License
for more details.

You should have received a copy of the GNU General Public License
along with this program; if not, see <http://www.gnu.org/licenses/>.
--------------------------------------------------------------------
Author: Hans Bihs
--------------------------------------------------------------------*/

#ifndef WAVE_LIB_WAVEMAKER2ND_H_
#define WAVE_LIB_WAVEMAKER2ND_H_

#include<vector>
#include<complex>

class lexer;
class ghostcell;

// Second-order wavemaker correction (Schaffer 1996) for piston, flap and
// double-flap wavemakers driven by paddle displacement time series.
//
// The first-order paddle signal is decomposed by FFT, the spurious free
// second-order waves (super- and subharmonic) generated by it are computed
// and the paddle displacement X^(2)(t) that cancels their progressive part
// is added to the input signal.
//
// A paddle consists of P = 1 or 2 linear segments, S(z,t) = sum_p X_p(t) f_p(z).
// For P = 2 (double flap) the correction is split over the two flaps in the
// same proportion (complex ratio) as the first-order motion, interpolated to
// the second-order frequency, so the lab's depth profile of the motion is kept.
//
// J = number of evanescent modes per frequency (0 = progressive modes only).
// addQ = 1: include the second-order paddle boundary terms
//           Q = X_z*phi_z - X*phi_xx (Taylor expansion about x=0).
//           Use this when the numerical paddle BC also contains Q (B119 1),
//           i.e. when it behaves like a physical moving paddle.
//        0: the numerical BC is phi_x = X_t exactly at x=0 (no Q),
//           so Q must not be cancelled by the correction either.

class wave_lib_wavemaker2nd
{
public:
    typedef std::complex<double> cplx;

    // paddle segment f(s) = al + be*s for s >= sa, 0 below (s = z+h)
    struct shape_t
    {
        double al, be, sa;
    };
    static shape_t shape_piston();
    static shape_t shape_flap(double zs, double ze);   // hinge zs, unit displacement at ze (from bed)

    wave_lib_wavemaker2nd();
    ~wave_lib_wavemaker2nd();

    // REEF3D interface: modifies kin[q][1] (displacement at the reference
    // elevation of the paddle) in place. shape: 1 piston, 2 flap
    void correct(lexer*, ghostcell*, double **kin, int ptnum, double h, int shape, double zs, double ze);

    // double flap: lower flap hinged at zs (kin[q][1] = displacement at z2),
    // upper flap hinged at z2 (kin[q][2] = displacement at ze relative to the lower flap)
    void correct_double(lexer*, ghostcell*, double **kin, int ptnum, double h, double zs, double z2, double ze);

    // REEF3D interface for the moving-paddle BC (B119): tabulates the
    // progressive-mode projection of Q(z,t) = X_z*phi_z - X*phi_xx at x=0,
    // computed from the linear paddle solution (progressive + J evanescent
    // modes) of the first-order signal.
    // Must be called with the uncorrected first-order signal.
    void make_Qtable(lexer*, ghostcell*, double **kin, int ptnum, double h, int shape, double zs, double ze);
    void make_Qtable_double(lexer*, ghostcell*, double **kin, int ptnum, double h, double zs, double z2, double ze);

    // Q at time t and elevation z (relative to still water level)
    double paddle_Q(double t, double z) const;

    // ---- core, general paddle (P segments) ----

    // first-order components on an integer frequency grid omega_n = bin[n]*dw,
    // X[p][n]: amplitude of segment p, X_p(t) = sum_n Re(X[p][n] exp(i omega_n t)).
    // Returns X2[p][b], second-order amplitudes on bins b = 0..2*max(bin).
    static void compute_components_multi(double g, double h, const std::vector<shape_t> &shp,
                       int mode, int J, int addQ, double dw, double w2min,
                       const std::vector<int> &bin, const std::vector<std::vector<cplx> > &X,
                       std::vector<std::vector<cplx> > &X2, std::vector<cplx> *RQ=nullptr);

    // uniformly sampled first-order displacements x[p] (dt), returns x2[p]
    // mode: 1 sub+super, 2 subharmonics only, 3 superharmonics only
    // fmin,fmax [Hz]: band of first-order components (fmax<=0: automatic)
    // f2min [Hz]: lowest corrected second-order frequency (<=0: 0.1 x peak frequency)
    // returns number of first-order components used
    static int compute_multi(double g, double h, const std::vector<shape_t> &shp,
                       int mode, int J, int addQ, double fmin, double fmax, double f2min, int nmax,
                       const std::vector<std::vector<double> > &x, double dt, std::vector<std::vector<double> > &x2);

    // progressive-mode projection of Q on nlev equidistant levels s=z+h in [0,h], Q[l*npts+q]
    static void compute_paddle_Q_multi(double g, double h, const std::vector<shape_t> &shp,
                       int J, double fmin, double fmax, int nmax,
                       const std::vector<std::vector<double> > &x, double dt, int nlev, std::vector<float> &Q);

    // ---- core, single segment (shape: 1 piston, 2 flap; zs,ze from the bed) ----
    static int compute(double g, double h, int shape, double zs, double ze,
                       int mode, int J, int addQ, double fmin, double fmax, double f2min, int nmax,
                       const std::vector<double> &x, double dt, std::vector<double> &x2);

    static void compute_components(double g, double h, int shape, double zs, double ze,
                       int mode, int J, int addQ, double dw, double w2min,
                       const std::vector<int> &bin, const std::vector<double> &Xre, const std::vector<double> &Xim,
                       std::vector<double> &X2re, std::vector<double> &X2im);

    static void compute_paddle_Q(double g, double h, int shape, double zs, double ze,
                       int J, double fmin, double fmax, int nmax,
                       const std::vector<double> &x, double dt, int nlev, std::vector<float> &Q);

private:
    static int resample(double **kin, int ptnum, int col, double &t0, double &dt, std::vector<double> &xu);

    void correct_impl(lexer*, ghostcell*, double **kin, int ptnum, double h,
                      const std::vector<shape_t> &shp, const std::vector<int> &col);
    void make_Qtable_impl(lexer*, ghostcell*, double **kin, int ptnum, double h,
                      const std::vector<shape_t> &shp, const std::vector<int> &col);

    std::vector<float> Qtab;
    int Qnlev=0, Qnt=0;
    double Qt0=0.0, Qdt=1.0, Qh=1.0;
};

#endif
